language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: bKpzQ70odi1gSiHxcdJ4H8p36gHpxV7jLeoVrSzisAw+qXuWNZuOhT6MJjZTBnnpIUjfZRL8s8y8t5+Xioeq3PuqM1tA3R3upPwLf3N2MzEbDakqdadJot2AJsPdbI1KMYtwkSyYk0bUcWbxIcEfFvq4ioY0EVsFOdscdF6OJjYjFC6FIEBGL9oPvr4I5odrq0OM+3prhjJ7YIF+QA3S2DsE0BLgJE/xOB95rseSGH2nsfo5EPc2hcC1nvQFhFuwDFKPdE8rH0Dx/4hvAGPvAo4VfcHAgrYeXfZl3D0bZIHr57W6jD9qNvkZOsWd4cCkI28o4Ml6SzXffLuJQ9FblbuzNk+8hEwdvPy3uuttwE6wq8k+2Sv9zrSAqtQkNPg6IClwPU54W+dBGcv9XH/M16M4CoPq7djHunbFLIFBv5hglF72p5zi7txB/Ab/z4o3DhKK8VErCdZ0UlDp13R8FGphrgGGxkeA3kR5vLMQ1+5yu/0das5qcJ6orLg3Dk+V/TskqZmA/s1lbZPp1rhHJ+7FE2SvPf7hECui7UW0YHWYKIhzpad3RlJDMHJijByG0hqnSiVMs4NstnPxntatMLzY4f+iZbN2rDQUbISFy7x3UBiO0ZV/o8hz3tagiYKQRaKJyAYCM/y9OiLmDftZ7oqa9Jc9AOaMqJ+2euNeZHU=
  app: Lpa2Automne2018
  on:
    repo: EdwigeChristelle/Lpa2Automne2018

  app: Lpa2Automne2018
  on:
    repo: EdwigeChristelle/Lpa2Automne2018
