 global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
language: ruby
rvm:
- 2.4.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
deploy:
  provider: heroku
  api_key:
    secure: Kgzoy5rdHdk4oCRCbg+7+KCZtTH8UYpm0VT0nuiQ3uybNdNLYdXVB8nYGhVTglJMI6fG81/eM+pr6ieDLeSSj8zk1eVy/oWTIFq+dh7qJA1OMIGE32q/lmFFMNQRAb8Ly8fKEF6BehHcrsT0kxgcYiWGY0g88+cLIvuMMbgrbmMWHvztPnHo1Bj7NojUqc/VF4WWbUL9pRXReEosgAN8ZZ7WR6RG+lCrFWJFs/rLNwTTI6cLP6AOg3Fk0HF59JCtPCLKhRle86pUdBZXIEMSn+qPrqBjES2rimORM/dCE0zWB/nEEMVsT9ud02iWqvAxzjWc+mY1qXtCLlEnWSpXbKRYpcFNpKI9kHwF/PkqDHvhI0+CJwnVRcJQU5qVr5/fzMYEzKTXwBk2ZIeXtzwBAjVmieb/332PIy6ebzkeSpKGfbNrVIWzPyfeOZpQTXFFKUFpv3kvmN89GMxKT+wscHS1FGVuKkTLiq9918viWljltgKTNWaJvR7O3HEls2ITkSerN77z7p1vsT3S8YPx9uCzy03c5laBeVwPUBj5Nr3/q735tgy3p5WN0pTgwdsYXMEyvob2Zfq9oy3xmiLOqNJD3bRmKS1T9puUN+W6QNJfkLVME2WrmxevtvHaAJRbMUHLCNQxid52dsY2fSFex3cVFEmuhbUd5jl4xfRnwas=
  app: gestionpizza
  on:
    repo: EdwigeChristelle/Lpa2Automne2018
    after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
