# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5d30d47f2989eaf16b3607e1f95f8606e6fb4c4dd66a1ac5b06559496c2c44b11df75d4a3bda5978659d178ef6cc8b524c1a10e2fa3904377be8bb4a931077

test:
  secret_key_base: 804ff585ecfce73a8bc73390ee5d6489ed1790730bc992cb018202e581b48f72e875d5e2ecde51580b1109f22501c26e942d7f39a221b13da3299de6416d609d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
